version: "3"

services:
    node-short-url:
        image: caomeiyouren/node-short-url
        restart: always
        ports:
            - "5000:5000"
        environment:
            PORT: 5000
            NODE_ENV: production
            REDIS_URL: "redis://redis:6379/"
            REDIS_HOST: "redis"
            REDIS_PORT: 6379
        depends_on:
            - redis
    redis:
        image: redis:alpine
        restart: always
        volumes:
            - redis-data:/data
volumes:
    redis-data:
